# Generated by Django 3.1.5 on 2021-03-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_searchbyisbn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchByISBN',
            new_name='Meal',
        ),
    ]
